default_twitter: &default_twitter
  twitter_api_key: <%= ENV['TWITTER_KEY'] %>
  twitter_api_secret: <%= ENV['TWITTER_SECRET'] %>

development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE']
  <<: *default_twitter

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE']
  <<: *default_twitter

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE']
  <<: *default_twitter
