default_twitter: &default_twitter
  twitter_api_key: <%= ENV['TWITTER_KEY'] %>
  twitter_api_secret: <%= ENV['TWITTER_SECRET'] %>

development:
  secret_key_base: 5568b371f5e08e89d29ffede50260f017f8bd6a0e0e5c22b4cc155cbbf579c6c36ddde40bdab3a1b72dcf999af00e6c1d18201671705381ffa057269a0709f73
  <<: *default_twitter
